title = "Тарас ПРО"
baseURL = "https://ua.tarasmatsyk.com"
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"]

[Params]
    tagline = "Привіт, мене звати Тарас"
    author = "Тарас Мацик"
    description = "Писака. Експерементатор. Ще той гівнюк."
    logoBigDes = ["Писака.","Експерементатор.","Ще той гівнюк."]
    logoBig = "/images/logo.png"
    logoSmall = "/images/logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/logo.png"
    twitter = "tarasmatsyk"
    linkedin = "tarasmatsyk"
    facebook = "tamatsyk"
    email = "hello@tarasmatsyk.com"
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    mailchimp = true

[[menu.main]]
    name = "Хто я"
    url  = "/#about"
    weight = 1
# [[menu.main]]
#     name = "Тут я пишу"
#     url  = "/#blog"
#     weight = 2
[[menu.main]]
    name = "Підписатися"
    url  = "/#subscribe"
    weight = 2