title = "Тарас Мовить"
baseURL = "https://ua.tarasmatsyk.com"
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-114670279-1"
disqusShortname = "ua-tarasmatsyk"
disableKinds = ["taxonomy", "taxonomyTerm"]

[Params]
    tagline = "Привіт, мене звати Тарас"
    author = "Тарас Мацик"
    description = "Писака. Експериментатор. Ще той гівнюк."
    logoBigDes = ["Писака.","Експериментатор.","Ще той гівнюк."]
    logoBig = "/images/logo.png"
    logoSmall = "/images/logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/logo.png"
    twitter = "tarasmatsyk"
    # linkedin = "tarasmatsyk"
    facebook = "tamatsyk"
    email = "tamatsyk@gmail.com"
    googleTagManager = ""
    dateform = "2006-01-02"
    highlightJS = true
    copyright = false
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    mailchimp = true

[[menu.main]]
    name = "Хто я"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Тут я пишу"
    url  = "/#blog"
    weight = 2
[[menu.main]]
    name = "Підписатися"
    url  = "/#subscribe"
    weight = 3
